---
- hosts: tomcatServers
  vars:
    war_url: http://172.31.37.250:8081/repository/maven-snapshots/com/maven/SimpleWebApplication/1.0.0-SNAPSHOT/maven-metadata.xml
    nexus_username: "'{{ lookup('env', 'nexus_username') }}'"
    nexus_password: "'{{ lookup('env', 'nexus_password') }}'"
  become_user: tomcat1
  become: true
  roles:
    - stopTomcat
    - takeBackup
    - downloadwar
    - startTomcat